version: '3'

services:
  db:
    container_name: db-news
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: news
      POSTGRES_PASSWORD: news
      POSTGRES_DB: news_db
    networks:
      - db-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U news -d news_db -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    container_name: producer-news
    build:
      context: .
      dockerfile: Dockerfile.spider
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-network

networks: 
  db-network:
    driver: bridge 