FROM python:3.9.12-slim

WORKDIR /app
 
# Copy the file from the local host to the filesystem of the container at the working directory.
COPY ./news /app/news


RUN apt-get update && \
    apt-get install -y libpq-dev gcc

# Install any needed packages specified in requirements.txt
RUN python3 -m pip install -r news/requirements.txt --no-cache-dir

# Change the working directory
WORKDIR /app/news

# Run spider crawl
CMD ["scrapy", "crawl", "news"]